"""Step 3a: build the human-simulation form (annotation/), blind to the questions.

  python build_form.py [--n 20]    # reads out/attr/questions.csv, writes out/human/items.csv and annotation.zip

The annotator plays the page describer of Idea 5. For each target page (a gold page), stage 1 shows the page alone
and asks for a search-index description; stage 2 adds the 3 most similar pages of the same document (by ColQwen
page-to-page similarity) and asks for a description that also tells the target apart from them. The question is
never shown: the describer works at index time, before any question exists.

Items, in this order until --n are taken (at most 2 per document, one item per gold page):
  A  look-alike misses (the page that beat the gold page is one of its 3 nearest look-alikes)
  B  other misses, except page references, gold pages with the closest look-alikes (highest nn_z) first
  C  hits whose gold page has a close look-alike (nn_z in the top quarter), highest nn_z first
Two practice items (P1, P2) come from documents outside the sample.
"""
import argparse
import json
import os
import re
import shutil
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

from common import IDEA5, OUT, SEED, page_image_path

FORM = Path(os.environ.get("IDEA5_FORM", IDEA5 / "annotation"))
IMG = FORM / "img"
ZIP = FORM.parent / "annotation.zip"
HUMAN = OUT / "human"
MAX_PER_DOC = 2
SIB_SIDE = 1100  # sibling images are downscaled to keep the zip small


def select(df, n, rng):
    df = df.copy()
    df["neighbours"] = df["neighbours"].map(json.loads)
    df = df[df["neighbours"].map(len) == 3]
    q75 = df["nn_z"].quantile(0.75)
    a = df[df["miss"] & (df["cause"] == "look-alike")].sort_values("nn_z", ascending=False)
    b = df[df["miss"] & ~df["cause"].isin(["look-alike", "page ref"])].sort_values("nn_z", ascending=False)
    c = df[~df["miss"] & (df["nn_z"] >= q75)].sort_values("nn_z", ascending=False)
    taken, per_doc, pages = [], {}, set()
    for group, cand in [("A", a), ("B", b), ("C", c)]:
        for _, r in cand.iterrows():
            key = (r["doc_id"], r["best_gold"])
            if len(taken) >= n or per_doc.get(r["doc_id"], 0) >= MAX_PER_DOC or key in pages:
                continue
            taken.append({**r.to_dict(), "group": group})
            per_doc[r["doc_id"]] = per_doc.get(r["doc_id"], 0) + 1
            pages.add(key)
    real = pd.DataFrame(taken)
    rest = c[~c["doc_id"].isin(set(real["doc_id"]))]
    rest = rest.drop_duplicates("doc_id")
    practice = rest.iloc[rng.permutation(len(rest))[:2]].assign(group="practice")
    real = real.iloc[rng.permutation(len(real))].reset_index(drop=True)
    real["item_id"] = [f"H{i + 1:02d}" for i in range(len(real))]
    practice = practice.reset_index(drop=True)
    practice["item_id"] = [f"P{i + 1}" for i in range(len(practice))]
    return pd.concat([practice, real], ignore_index=True)


def copy_page(doc_id, page, dst, max_side=None):
    img = Image.open(page_image_path(doc_id, page)).convert("RGB")
    if max_side and max(img.size) > max_side:
        img.thumbnail((max_side, max_side), Image.BICUBIC)
    img.save(dst, quality=88)


def build(n):
    rng = np.random.default_rng(SEED)
    df = pd.read_csv(OUT / "attr" / "questions.csv")
    items = select(df, n, rng)
    HUMAN.mkdir(parents=True, exist_ok=True)
    keep = ["item_id", "group", "qid", "doc_id", "doc_type", "n_pages", "best_gold", "neighbours", "best_rank",
            "winner", "cause", "nn_z", "question"]
    out = items[keep].rename(columns={"best_gold": "target"})
    out["neighbours"] = out["neighbours"].map(json.dumps)
    out.to_csv(HUMAN / "items.csv", index=False)

    if IMG.exists():
        shutil.rmtree(IMG)
    IMG.mkdir(parents=True)
    shutil.copyfile(IDEA5 / "form_template.html", FORM / "index.html")
    js_items = []
    for r in items.itertuples():
        copy_page(r.doc_id, r.best_gold, IMG / f"{r.item_id}_t.jpg")
        for k, p in enumerate(r.neighbours, 1):
            copy_page(r.doc_id, p, IMG / f"{r.item_id}_s{k}.jpg", SIB_SIDE)
        js_items.append({"item_id": r.item_id, "practice": r.group == "practice", "doc_type": r.doc_type,
                         "n_pages": int(r.n_pages), "target_page": int(r.best_gold),
                         "sibling_pages": [int(p) for p in r.neighbours]})
    js = ("// Generated by build_form.py. Do not edit.\n"
          f"window.ITEMS = {json.dumps(js_items, indent=1, ensure_ascii=False)};\n")
    (FORM / "items.js").write_text(js, encoding="utf-8")
    check(items)

    if ZIP.exists():
        ZIP.unlink()
    with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
        for p in sorted(FORM.rglob("*")):
            if p.is_file():
                z.write(p, p.relative_to(FORM.parent))
    print(items.groupby("group").size().to_dict())
    print(f"wrote {HUMAN / 'items.csv'} and {ZIP} ({ZIP.stat().st_size / 1e6:.1f} MB)")


def check(items):
    """items.js parses, every image exists, and no question, answer or document name is in the folder."""
    js = (FORM / "items.js").read_text(encoding="utf-8")
    parsed = json.loads(re.search(r"window\.ITEMS = (\[.*\]);\s*$", js, re.S).group(1))
    assert [it["item_id"] for it in parsed] == list(items["item_id"])
    allowed = {"item_id", "practice", "doc_type", "n_pages", "target_page", "sibling_pages"}
    assert all(set(it) == allowed for it in parsed)
    want = sorted(f"{i}_{s}.jpg" for i in items["item_id"] for s in ["t", "s1", "s2", "s3"])
    assert sorted(p.name for p in IMG.iterdir()) == want
    blob = "\n".join(p.read_text(encoding="utf-8", errors="ignore") for p in FORM.rglob("*")
                     if p.is_file() and p.suffix in (".js", ".html", ".css", ".json", ".txt")).lower()
    leaks = [(r.item_id, "question") for r in items.itertuples() if r.question.lower()[:60] in blob]
    leaks += [(r.item_id, "document") for r in items.itertuples() if r.doc_id.lower() in blob]
    if leaks:
        raise SystemExit(f"LEAK: {leaks}")
    print(f"checks: {len(parsed)} items, {len(want)} images, no question or document name in annotation/")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=20)
    build(ap.parse_args().n)
