// Generated by build_form.py. Do not edit.
window.INVENTORY_SOURCE = "vlm";
window.ITEMS = [
 {
  "item_id": "P1",
  "practice": true,
  "question": "list the top-3 models in Figure 3",
  "doc_type": "Academic paper",
  "n_pages": 77,
  "inventory": "Contains charts on 13 pages (bar 9, line 7, scatter 2), tables on 41 pages, figures on 19 pages (other 17, screenshot 4, diagram or flowchart 1), and text on 64 pages. Style: white, black, blue, serif, monospace.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIlsnVmljdW5hMTNiLXYxLjMnLCAnUGFMTSBCaXNvbicsICdWaWN1bmExM2ItdjEuMSddIiwgImdvbGRfcGFnZSI6IDR9"
 },
 {
  "item_id": "P2",
  "practice": true,
  "question": "How much higher is the accuracy of PaLM-2L + RAG compared to PaLM-2L on TimeQA?",
  "doc_type": "Academic paper",
  "n_pages": 36,
  "inventory": "Contains no charts, tables on 28 pages, figures on 6 pages (other 8, diagram or flowchart 1), and text on 29 pages. Style: white, black, serif, simple, blue.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIjE1LjklIiwgImdvbGRfcGFnZSI6IDZ9"
 },
 {
  "item_id": "P3",
  "practice": true,
  "question": "who is the presenter of this slide?",
  "doc_type": "Tutorial/Workshop",
  "n_pages": 20,
  "inventory": "Contains charts on 11 pages (bar 10, line 1), tables on 5 pages, figures on 3 pages (diagram or flowchart 2, photo 1, screenshot 1), and text on 13 pages. Style: white, red, blue, black, bars.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGV4dCIsICJnb2xkX3NvdXJjZSI6ICJQdXJlLXRleHQgKFBsYWluLXRleHQpIiwgImFuc3dlciI6ICJEYXZpZCBMdWJsaW5lciIsICJnb2xkX3BhZ2UiOiAxfQ=="
 },
 {
  "item_id": "A01",
  "practice": false,
  "question": "What range does red color represents in approximate distance from the Mississippi River in the chart that tracks the West NIle Virus in Europe?",
  "doc_type": "Tutorial/Workshop",
  "n_pages": 15,
  "inventory": "Contains charts on 7 pages (line 4, bar 2, pie or donut 2), tables on 6 pages, figures on 7 pages (diagram or flowchart 6, other 6, map 2), and text on 9 pages. Style: black, white, red, header, blue.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIjAtMzc1IG1pbGVzIiwgImdvbGRfcGFnZSI6IDEwfQ=="
 },
 {
  "item_id": "A02",
  "practice": false,
  "question": "What position is the man with the red shirt in the figure on the last page, directly answer 'bottom', 'middle' or 'top'?",
  "doc_type": "Tutorial/Workshop",
  "n_pages": 77,
  "inventory": "Contains no charts, tables on 2 pages, figures on 48 pages (diagram or flowchart 29, photo 19, other 2, screenshot 2, illustration or icon 1), and text on 73 pages. Style: blue, white, green, header, medical.",
  "gold": "eyJnb2xkX3R5cGUiOiAiZmlndXJlIiwgImdvbGRfc291cmNlIjogIkZpZ3VyZSIsICJhbnN3ZXIiOiAiYm90dG9tIiwgImdvbGRfcGFnZSI6IDc3fQ=="
 },
 {
  "item_id": "A03",
  "practice": false,
  "question": "What is thed dental telephone number for fullerton healthcare at NTU?",
  "doc_type": "Guidebook",
  "n_pages": 44,
  "inventory": "Contains no charts, tables on 21 pages, figures on 24 pages (photo 51, map 1, illustration or icon 1), and text on 41 pages. Style: white, blue, header, black, modern.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIig2NSkgNjc5MCA4MzMxIiwgImdvbGRfcGFnZSI6IDE5fQ=="
 },
 {
  "item_id": "A04",
  "practice": false,
  "question": "Does llama-1 apply qknorm? Directly answer 'yse' or 'no'",
  "doc_type": "Academic paper",
  "n_pages": 27,
  "inventory": "Contains charts on 4 pages (line 6, bar 3), tables on 11 pages, figures on 8 pages (photo 11, other 5, diagram or flowchart 2), and text on 23 pages. Style: white, black, serif, blue, modern.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIm5vIiwgImdvbGRfcGFnZSI6IDh9"
 },
 {
  "item_id": "A05",
  "practice": false,
  "question": "In the figure at Page at the second last, howm many people are standing? ",
  "doc_type": "Brochure",
  "n_pages": 17,
  "inventory": "Contains no charts, tables on 9 pages, figures on 13 pages (photo 21, illustration or icon 4), and text on 16 pages. Style: white, black, blue, red, light.",
  "gold": "eyJnb2xkX3R5cGUiOiAiZmlndXJlIiwgImdvbGRfc291cmNlIjogIkZpZ3VyZSIsICJhbnN3ZXIiOiAiMSIsICJnb2xkX3BhZ2UiOiAxNn0="
 },
 {
  "item_id": "A06",
  "practice": false,
  "question": "According to this report,  what percentage of Germany respondent view China or Japan as the top economic power? Give me a percantage value.",
  "doc_type": "Research report / Introduction",
  "n_pages": 21,
  "inventory": "Contains charts on 13 pages (bar 12, line 2), tables on 6 pages, no figures, and text on 18 pages. Style: white, black, blue, modern, design.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIjU5JSIsICJnb2xkX3BhZ2UiOiAxNn0="
 },
 {
  "item_id": "A07",
  "practice": false,
  "question": "According to the chart on page 14 how much time was spent with family and friends in 2010?",
  "doc_type": "Tutorial/Workshop",
  "n_pages": 15,
  "inventory": "Contains charts on 7 pages (line 4, bar 2, pie or donut 2), tables on 6 pages, figures on 7 pages (diagram or flowchart 6, other 6, map 2), and text on 9 pages. Style: black, white, red, header, blue.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIjIxJSIsICJnb2xkX3BhZ2UiOiAxNH0="
 },
 {
  "item_id": "A08",
  "practice": false,
  "question": "What is the title of case study given under unit-8 in table?",
  "doc_type": "Administration/Industry file",
  "n_pages": 17,
  "inventory": "Contains no charts, tables on 2 pages, no figures, and text on 15 pages. Style: white, black, serif, simple.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGV4dCIsICJnb2xkX3NvdXJjZSI6ICJQdXJlLXRleHQgKFBsYWluLXRleHQpIiwgImFuc3dlciI6ICJEaXNjcmltaW5hdGlvbiBpbiB0aGUgV29ya3BsYWNlIENvbnRpbnVlcyIsICJnb2xkX3BhZ2UiOiA3fQ=="
 },
 {
  "item_id": "A09",
  "practice": false,
  "question": "What kind of albums are reducing the share of their business due to streaming?",
  "doc_type": "Research report / Introduction",
  "n_pages": 36,
  "inventory": "Contains charts on 10 pages (bar 9, stacked bar 1, line 1, area 1), tables on 11 pages, figures on 12 pages (photo 6, diagram or flowchart 3, other 2, screenshot 1), and text on 27 pages. Style: blue, white, dark, bars, lines.",
  "gold": "eyJnb2xkX3R5cGUiOiAiZmlndXJlIiwgImdvbGRfc291cmNlIjogIkZpZ3VyZSIsICJhbnN3ZXIiOiAiWydQaHlzaWNhbCBhbGJ1bXMnLCAnRGlnaXRhbCBhbGJ1bXMnLCAnRGlnaXRhbCB0cmFja3MnXSIsICJnb2xkX3BhZ2UiOiA2fQ=="
 },
 {
  "item_id": "A10",
  "practice": false,
  "question": "Among all the emotions that social media makes users feel, what was the 4th most popular emotion?",
  "doc_type": "Research report / Introduction",
  "n_pages": 30,
  "inventory": "Contains charts on 7 pages (bar 6, pie or donut 1), tables on 11 pages, no figures, and text on 26 pages. Style: white, black, simple, blue, bars.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIkluc3BpcmVkIiwgImdvbGRfcGFnZSI6IDIyfQ=="
 },
 {
  "item_id": "A11",
  "practice": false,
  "question": "How many languages are shown in the in-context examples for multi-lingual translation query?",
  "doc_type": "Academic paper",
  "n_pages": 22,
  "inventory": "Contains charts on 1 page (bar 3), tables on 12 pages, figures on 5 pages (other 4, diagram or flowchart 2, photo 1, screenshot 1), and text on 16 pages. Style: white, black, blue, simple, header.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIjgiLCAiZ29sZF9wYWdlIjogMTZ9"
 },
 {
  "item_id": "A12",
  "practice": false,
  "question": "What is Netflix working capital in FY2015?Answer in thousands.",
  "doc_type": "Financial report",
  "n_pages": 72,
  "inventory": "Contains charts on 1 page (line 1), tables on 36 pages, figures on 1 page (other 1), and text on 59 pages. Style: white, black, blue, links, simple.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIjE5MDIyMTYuMDAiLCAiZ29sZF9wYWdlIjogNDN9"
 },
 {
  "item_id": "A13",
  "practice": false,
  "question": "On the left or right side of the screen, can you immediately find information about the percentage of the total available students represented by your chosen search criteria? Answer 'left' or 'right'.",
  "doc_type": "Guidebook",
  "n_pages": 18,
  "inventory": "Contains no charts, tables on 9 pages, figures on 8 pages (map 7, screenshot 4, photo 1), and text on 15 pages. Style: white, header, black, serif, gold.",
  "gold": "eyJnb2xkX3R5cGUiOiAiZmlndXJlIiwgImdvbGRfc291cmNlIjogIkZpZ3VyZSIsICJhbnN3ZXIiOiAiUmlnaHQiLCAiZ29sZF9wYWdlIjogMTd9"
 },
 {
  "item_id": "A14",
  "practice": false,
  "question": "When did the number of tweets referencing Germanwings exceed 200,000? Your report time should be in CET time, like '17:05 CET'.",
  "doc_type": "Research report / Introduction",
  "n_pages": 23,
  "inventory": "Contains charts on 3 pages (line 6), tables on 9 pages, figures on 19 pages (screenshot 31, photo 8, map 1), and text on 23 pages. Style: white, black, red, logo, blue.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIjE0OjA0IENFVCIsICJnb2xkX3BhZ2UiOiAxOX0="
 },
 {
  "item_id": "A15",
  "practice": false,
  "question": "Where are the two plants of GODFREY PHILLIPS INDIA LIMITED located?",
  "doc_type": "Financial report",
  "n_pages": 20,
  "inventory": "Contains charts on 2 pages (bar 1, line 1), tables on 10 pages, no figures, and text on 15 pages. Style: white, black, serif, pink, header.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGV4dCIsICJnb2xkX3NvdXJjZSI6ICJQdXJlLXRleHQgKFBsYWluLXRleHQpIiwgImFuc3dlciI6ICJbJ1YuSy5LLiBNRU5PTiBST0FEIChTQUhBUiBST0FEKSxDSEFLQUxBLEFOREhFUkkgKEVBU1QpLE1VTUJBSS00MDAwOTknLCAnSW50ZXJuYXRpb25hbCBUb2JhY2NvIENvbXBhbnkgTHRkLiBEZWxoaS0gTWVlcnV0IFJvYWQsIEd1bGRoYXIsIEdoYXppYWJhZCddIiwgImdvbGRfcGFnZSI6IDE1fQ=="
 },
 {
  "item_id": "A16",
  "practice": false,
  "question": "How many Tweets are attributed to Germanwings, Lufthansa, and Airbus in total?",
  "doc_type": "Research report / Introduction",
  "n_pages": 23,
  "inventory": "Contains charts on 3 pages (line 6), tables on 9 pages, figures on 19 pages (screenshot 31, photo 8, map 1), and text on 23 pages. Style: white, black, red, logo, blue.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIjQxIiwgImdvbGRfcGFnZSI6IDE2fQ=="
 },
 {
  "item_id": "A17",
  "practice": false,
  "question": "According to the survey on April 25 - May 1, 2018, what are the domains with the highest percentage that adults are very confident and not at all confident of Donald Trump's govenment? Please write the answer in the list format and with alphabetical order, e.g., [\"A\",\"B\"]",
  "doc_type": "Research report / Introduction",
  "n_pages": 17,
  "inventory": "Contains charts on 7 pages (bar 6, line 1), tables on 7 pages, no figures, and text on 16 pages. Style: white, black, serif, simple, text-based.",
  "gold": "eyJnb2xkX3R5cGUiOiAiY2hhcnQiLCAiZ29sZF9zb3VyY2UiOiAiQ2hhcnQiLCAiYW5zd2VyIjogIlsnTWFrZSBnb29kIGRlY2lzaW9ucyBhYm91dCBlY29ub21pYyBwb2xpY3kgJywgJ01ha2Ugd2lzZSBkZWNpc2lvbnMgYWJvdXQgaW1taWdyYXRpb24gcG9saWN5ICddIiwgImdvbGRfcGFnZSI6IDV9"
 },
 {
  "item_id": "A18",
  "practice": false,
  "question": "How many districts were sampled during Wave III?",
  "doc_type": "Research report / Introduction",
  "n_pages": 44,
  "inventory": "Contains charts on 25 pages (bar 23, pie or donut 8), tables on 10 pages, figures on 8 pages (photo 6, diagram or flowchart 3, illustration or icon 2, map 1), and text on 19 pages. Style: white, simple, blue, design, dark.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGFibGUiLCAiZ29sZF9zb3VyY2UiOiAiVGFibGUiLCAiYW5zd2VyIjogIjQ0IiwgImdvbGRfcGFnZSI6IDl9"
 },
 {
  "item_id": "A24",
  "practice": false,
  "question": "What type of court is noted on the cover page?",
  "doc_type": "Administration/Industry file",
  "n_pages": 15,
  "inventory": "Contains no charts, tables on 3 pages, no figures, and text on 15 pages. Style: white, black, serif.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGV4dCIsICJnb2xkX3NvdXJjZSI6ICJQdXJlLXRleHQgKFBsYWluLXRleHQpIiwgImFuc3dlciI6ICJTVVBFUklPUiBDT1VSVCIsICJnb2xkX3BhZ2UiOiAxfQ=="
 },
 {
  "item_id": "A28",
  "practice": false,
  "question": "What is the web link to this paper?",
  "doc_type": "Academic paper",
  "n_pages": 20,
  "inventory": "Contains no charts, tables on 3 pages, figures on 11 pages (diagram or flowchart 14, other 1), and text on 18 pages. Style: white, black, structured, serif, simple.",
  "gold": "eyJnb2xkX3R5cGUiOiAidGV4dCIsICJnb2xkX3NvdXJjZSI6ICJQdXJlLXRleHQgKFBsYWluLXRleHQpIiwgImFuc3dlciI6ICJodHRwOi8vZHguZG9pLm9yZy8xMC4xMDE2L2ouZWptaGcuMjAxNS4wNy4wMDIiLCAiZ29sZF9wYWdlIjogMX0="
 }
];
