"""Step 3: write annotation/items.js, copy the gold page images, run the blindness checks, zip the folder.

  python build_form.py                    # inventory from out/inventory/docs.json (VLM pass)
  python build_form.py --inventory labels # fallback: evidence types of the document's other questions
  python build_form.py --items A01-A18,A24,A28   # only these real items (practice items are always kept)
"""
import argparse
import json
import re
import shutil
import zipfile
from collections import Counter

import pandas as pd

from common import IDEA4, OUT, SOURCE_TO_TYPE, b64, doc_stem, load_qa, page_image_path, unb64

FORM = IDEA4 / "annotation"
IMG = FORM / "img"
ZIP = IDEA4 / "annotation.zip"
PLURAL = {"chart": "charts", "table": "tables", "figure": "figures", "text": "text"}


def pages_phrase(t, n, subtypes=None):
    s = f"{PLURAL[t]} on {n} page{'s' if n != 1 else ''}"
    if subtypes:
        s += " (" + ", ".join(f"{k} {v}" for k, v in subtypes.items()) + ")"
    return s


def vlm_inventory(inv):
    """Plain sentence from the per-document VLM counts."""
    parts = []
    for t in ["chart", "table", "figure", "text"]:
        n = inv["pages_with_type"].get(t, 0)
        if n == 0:
            parts.append(f"no {PLURAL[t]}")
            continue
        sub = inv.get(f"{t}_subtypes") if t in ("chart", "figure") else None
        parts.append(pages_phrase(t, n, sub))
    s = "Contains " + ", ".join(parts[:-1]) + ", and " + parts[-1] + "."
    if inv["style_words"]:
        s += " Style: " + ", ".join(inv["style_words"]) + "."
    return s


def labels_inventory(qa, item):
    """Evidence types of the document's other answerable questions, without page numbers."""
    other = qa[(qa["doc_id"] == item["doc_id"]) & qa["answerable"] & (qa["qid"] != item["qid"])]
    c = Counter(SOURCE_TO_TYPE[s] for srcs in other["ev_sources"] for s in set(srcs))
    if not c:
        return "No other questions about this document."
    names = {"chart": "chart", "table": "table", "figure": "figure", "text": "pure text", "layout": "layout"}
    body = ", ".join(f"{names[t]} {n}" for t, n in c.most_common())
    return f"Other questions about this document ({len(other)} questions) use these evidence types: {body}."


def parse_items(spec):
    ids = []
    for part in spec.split(","):
        if "-" in part:
            a, b = part.split("-")
            ids += [f"A{i:02d}" for i in range(int(a[1:]), int(b[1:]) + 1)]
        else:
            ids.append(part.strip())
    return ids


def build(source, items_spec=None):
    sample = pd.read_csv(OUT / "sample.csv")
    if items_spec:
        keep = set(parse_items(items_spec))
        sample = sample[sample["practice"] | sample["item_id"].isin(keep)]
    # The form's item list, read by analyze_A.py for the majority baseline.
    (OUT / "form_items.txt").write_text("\n".join(sample["item_id"]) + "\n")
    qa = load_qa()
    docs_inv = json.loads((OUT / "inventory" / "docs.json").read_text()) if source == "vlm" else None

    if IMG.exists():
        shutil.rmtree(IMG)
    IMG.mkdir(parents=True)
    items = []
    for _, r in sample.iterrows():
        inv_text = vlm_inventory(docs_inv[r["doc_id"]]) if source == "vlm" else labels_inventory(qa, r)
        gold = {"gold_type": r["gold_type"], "gold_source": r["gold_source"], "answer": str(r["answer"]),
                "gold_page": int(r["gold_page"])}
        items.append({"item_id": r["item_id"], "practice": bool(r["practice"]), "question": r["question"],
                      "doc_type": r["doc_type"], "n_pages": int(r["n_pages"]), "inventory": inv_text,
                      "gold": b64(json.dumps(gold, ensure_ascii=False))})
        shutil.copyfile(page_image_path(r["doc_id"], int(r["gold_page"])), IMG / f"{r['item_id']}.jpg")

    js = ("// Generated by build_form.py. Do not edit.\n"
          f"window.INVENTORY_SOURCE = {json.dumps(source)};\n"
          f"window.ITEMS = {json.dumps(items, indent=1, ensure_ascii=False)};\n")
    (FORM / "items.js").write_text(js, encoding="utf-8")
    check(sample, source)

    if ZIP.exists():
        ZIP.unlink()
    with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
        for p in sorted(FORM.rglob("*")):
            if p.is_file():
                z.write(p, p.relative_to(FORM.parent))
    print(f"wrote {ZIP} ({ZIP.stat().st_size / 1e6:.1f} MB), inventory_source = {source}")


def check(sample, source):
    """items.js parses, every image exists, gold decodes, and no gold string leaks into the folder."""
    js = (FORM / "items.js").read_text(encoding="utf-8")
    m = re.search(r"window\.ITEMS = (\[.*\]);\s*$", js, re.S)
    items = json.loads(m.group(1))
    assert json.loads(re.search(r"window\.INVENTORY_SOURCE = (\".*?\");", js).group(1)) == source
    assert [it["item_id"] for it in items] == list(sample["item_id"])
    by_id = sample.set_index("item_id")
    for it in items:
        assert (IMG / f"{it['item_id']}.jpg").exists(), it["item_id"]
        g = json.loads(unb64(it["gold"]))
        assert g["answer"] == str(by_id.loc[it["item_id"], "answer"]) and g["gold_page"] == by_id.loc[it["item_id"], "gold_page"]
    assert sorted(p.name for p in IMG.iterdir()) == sorted(f"{i}.jpg" for i in sample["item_id"])
    # Structural check: items carry only these fields; gold is only inside the base64 blob.
    # This also covers short or numeric answers, which a string search cannot test.
    allowed = {"item_id", "practice", "question", "doc_type", "n_pages", "inventory", "gold"}
    assert all(set(it) == allowed for it in items)
    for it in items:
        r = by_id.loc[it["item_id"]]
        assert it["question"] == r["question"] and it["doc_type"] == r["doc_type"] and it["n_pages"] == r["n_pages"]

    # Plain-text leak check over every file in the folder. Item ids, image names and questions are visible by design,
    # so questions are removed before searching. Gold strings: document names, answers, evidence labels.
    blob = ""
    for p in FORM.rglob("*"):
        if p.is_file() and p.suffix in (".js", ".html", ".css", ".json", ".txt"):
            blob += p.read_text(encoding="utf-8", errors="ignore") + "\n"
    blob_noq = blob
    for q in sorted(sample["question"], key=len, reverse=True):
        blob_noq = blob_noq.replace(json.dumps(q, ensure_ascii=False)[1:-1], " ")
    low = blob_noq.lower()
    leaks, short, in_question = [], [], []
    for _, r in sample.iterrows():
        for s in [r["doc_id"], doc_stem(r["doc_id"])]:
            if s.lower() in low:
                leaks.append((r["item_id"], "doc", s))
        ans = str(r["answer"]).strip()
        if ans.lower() in r["question"].lower():
            in_question.append(r["item_id"])  # visible by design
        elif len(ans) < 6 or re.fullmatch(r"[\d.,%$\s-]+", ans):
            short.append(r["item_id"])  # too short or numeric to search for without false hits
        elif ans.lower() in low:
            leaks.append((r["item_id"], "answer", ans))
    # Evidence source labels appear in no visible text before step 3 (the form uses its own type names).
    for lab in ["Pure-text (Plain-text)", "Generalized-text (Layout)", "evidence_pages", "evidence_sources"]:
        if lab.lower() in low:
            leaks.append(("-", "label", lab))
    print(f"checks: {len(items)} items, {len(list(IMG.iterdir()))} images, gold decodes")
    print(f"answers too short or numeric for the string search (covered by the field check): {len(short)} items")
    if in_question:
        print(f"answers that appear in their own question (multiple choice, not a leak): {in_question}")
    if leaks:
        raise SystemExit(f"LEAK: {leaks}")
    print("no gold string found in plain text in annotation/")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", choices=["vlm", "labels"], default="vlm")
    ap.add_argument("--items", default=None)
    args = ap.parse_args()
    build(args.inventory, args.items)
