"""Part B: ColQwen2.5 retrieval within one document.

  CUDA_VISIBLE_DEVICES=0 python retrieve.py pages     # embeds every page of the sampled documents (cached)
  CUDA_VISIBLE_DEVICES=0 python retrieve.py queries   # embeds every query variant, scores all pages, writes out/partB/scores.jsonl

Query variants, per pool question (proposer/id_map.csv):
  q_text     the question as text
  spec_text  the proposer's specification written as text
  code_img   the specification drawn with matplotlib (renders/code/<pid>.png)
  gen_img    the specification generated by Qwen-Image (renders/gen/<pid>.png)
  qimg       the question rendered as an image (pixels without the specification)
  oracle     André's step-3 box cropped from the gold page (Part A items only)
  *_h        the same variants built from André's step-2 specs (Part A items only)
"""
import json
import sys

import pandas as pd
import torch
from PIL import Image

from common import IDEA4, OUT, doc_stem, page_image_path

MODEL = "vidore/colqwen2.5-v0.2"
EMB = IDEA4 / "cache" / "colqwen"
PDIR = IDEA4 / "proposer"
RENDERS = IDEA4 / "renders"
OUTB = OUT / "partB"
MAX_VISUAL_TOKENS = 768  # fixed resolution for pages and image queries
BATCH = 8


def load_model():
    from colpali_engine.models import ColQwen2_5, ColQwen2_5_Processor
    model = ColQwen2_5.from_pretrained(MODEL, dtype=torch.bfloat16, device_map="cuda",
                                       attn_implementation="sdpa").eval()
    proc = ColQwen2_5_Processor.from_pretrained(MODEL, max_num_visual_tokens=MAX_VISUAL_TOKENS)
    return model, proc


def embed_images(model, proc, images):
    out = []
    for k in range(0, len(images), BATCH):
        batch = proc.process_images(images[k:k + BATCH]).to(model.device)
        with torch.inference_mode():
            e = model(**batch)
        mask = batch["attention_mask"].bool()
        out += [e[i][mask[i]].to(torch.float16).cpu() for i in range(e.shape[0])]
    return out


def embed_texts(model, proc, texts):
    out = []
    for k in range(0, len(texts), BATCH):
        batch = proc.process_queries(texts[k:k + BATCH]).to(model.device)
        with torch.inference_mode():
            e = model(**batch)
        mask = batch["attention_mask"].bool()
        out += [e[i][mask[i]].to(torch.float16).cpu() for i in range(e.shape[0])]
    return out


def pages():
    model, proc = load_model()
    EMB.mkdir(parents=True, exist_ok=True)
    for d in (OUT / "sample_docs.txt").read_text().split():
        path = EMB / f"{doc_stem(d)}.pt"
        if path.exists():
            continue
        files = sorted((page_image_path(d, 1).parent).glob("*.jpg"))
        embs = embed_images(model, proc, [Image.open(f).convert("RGB") for f in files])
        torch.save(embs, path)  # one float16 tensor per page, [n_tokens, 128]
        print(d, len(embs), flush=True)


def spec_as_text(s):
    parts = []
    for k in ["subtype", "title", "x_label", "y_label", "caption", "heading", "passage", "description"]:
        if s.get(k):
            parts.append(str(s[k]))
    for k in ["categories", "series", "columns", "rows"]:
        if s.get(k):
            parts.append(", ".join(map(str, s[k])))
    if s.get("element"):
        parts.insert(0, s["element"])
    return ". ".join(parts)


def maxsim(q, pages_emb):
    """ColBERT late interaction: sum over query tokens of the max similarity over page tokens."""
    q = q.cuda().float()
    return [float((q @ p.cuda().float().T).max(dim=1).values.sum()) for p in pages_emb]


def oracle_crops(ids):
    """Crops of the step-3 boxes from the latest real export, keyed by item_id."""
    crops = {}
    for f in sorted((IDEA4 / "exports").glob("*.json")):
        data = json.loads(f.read_text())
        if "SYNTHETIC" in f.name or "SYNTHETIC" in data["annotator"]:
            continue
        for it in data["items"]:
            s3 = it.get("step3")
            if it["practice"] or not s3 or not s3.get("bbox"):
                continue
            r = ids[ids["item_id"] == it["item_id"]].iloc[0]
            img = Image.open(page_image_path(r["doc_id"], int(r["gold_page"]))).convert("RGB")
            w, h = img.size
            x0, y0, x1, y1 = s3["bbox"]
            crops[it["item_id"]] = img.crop((int(x0 * w), int(y0 * h), int(x1 * w), int(y1 * h)))
    return crops


def queries():
    model, proc = load_model()
    ids = pd.read_csv(PDIR / "id_map.csv")
    specs = {json.loads(l)["pid"]: json.loads(l) for l in (PDIR / "specs.jsonl").open()}
    variants = {"q_text": ("text", {r.pid: r.question for r in ids.itertuples()}),
                "spec_text": ("text", {p: spec_as_text(s["spec"]) for p, s in specs.items()})}
    hpath = PDIR / "human_specs.jsonl"
    if hpath.exists():  # André's step-2 specs (Part A items only)
        hspecs = {json.loads(l)["pid"]: json.loads(l) for l in hpath.open()}
        variants["spec_text_h"] = ("text", {p: spec_as_text(s["spec"]) for p, s in hspecs.items()})
    for name, sub in [("code_img", "code"), ("gen_img", "gen"), ("qimg", "question"),
                      ("code_img_h", "code_human"), ("gen_img_h", "gen_human")]:
        files = {f.stem: f for f in (RENDERS / sub).glob("*.png")}
        variants[name] = ("image", {p: Image.open(f).convert("RGB") for p, f in files.items()})
    crops = oracle_crops(ids)
    pid_of = dict(zip(ids["item_id"], ids["pid"]))
    variants["oracle"] = ("image", {pid_of[i]: c for i, c in crops.items()})

    doc_emb = {}
    OUTB.mkdir(parents=True, exist_ok=True)
    with (OUTB / "scores.jsonl").open("w") as f:
        for name, (kind, data) in variants.items():
            keys = list(data)
            if not keys:
                print(name, "no queries, skipped")
                continue
            embs = embed_texts(model, proc, [data[k] for k in keys]) if kind == "text" else \
                embed_images(model, proc, [data[k] for k in keys])
            for pid, q in zip(keys, embs):
                r = ids[ids["pid"] == pid].iloc[0]
                if r["doc_id"] not in doc_emb:
                    doc_emb[r["doc_id"]] = torch.load(EMB / f"{doc_stem(r['doc_id'])}.pt")
                f.write(json.dumps({"pid": pid, "variant": name, "scores": maxsim(q, doc_emb[r["doc_id"]])}) + "\n")
            print(name, len(keys), flush=True)


if __name__ == "__main__":
    {"pages": pages, "queries": queries}[sys.argv[1]]()
